# Generated by Django 4.2.23 on 2025-09-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="name",
            new_name="library_books_title",
        ),
    ]
